// 🟡 - Starters - 🟡
const menuStarters = [
  {
    img: "../images/starters/hot/Bacon-Wrapped-Zucchini.jpg",
    name: "Bacon-Wrapped Zucchini",
    compound:
      "Tender zucchini spears wrapped in crispy smoked bacon, roasted with garlic butter and provence herbs.",
    class: "startersHot",
    id: "starters",
    price: "7",
    gram: "150",
    calories: "320",
    spicy: 1,
    rating: 4.7,
  },
  {
    img: "../images/starters/hot/Exotic-Meat-Selection.jpg",
    name: "Exotic Meat Selection",
    compound:
      "A curated platter of premium deli meats, served with a signature berry reduction and toasted artisanal bread.",
    class: "startersHot",
    id: "starters",
    price: "14.5",
    gram: "200",
    calories: "480",
    spicy: 2,
    rating: 4.9,
  },
  {
    img: "../images/starters/cold/Garden-Fresh-Meat-Salad.jpg",
    name: "Fresh Meat Salad",
    compound:
      "Fresh garden greens mixed with tender boiled beef slices, juicy tomatoes, and cucumbers with an olive oil dressing.",
    class: "startersCold",
    id: "starters",
    price: "10",
    gram: "220",
    calories: "290",
    spicy: 0,
    rating: 4.5,
  },
  {
    img: "../images/starters/vegetarian/Golden-Pickled-Cucumbers.jpg",
    name: "Golden Cucumber",
    compound:
      "House-made pickles infused with turmeric, mustard seeds, and a spicy aromatic marinade for a signature golden hue.",
    class: "startersVegetarian",
    id: "starters",
    price: "5",
    gram: "120",
    calories: "60",
    spicy: 1,
    rating: 4.3,
  },
  {
    img: "../images/starters/vegetarian/Vegetable-salat.jpg",
    name: "Salat",
    compound:
      "A classic blend of seasonal vegetables: ripe tomatoes, bell peppers, red onions, and farm-fresh herbs.",
    class: "startersVegetarian",
    id: "starters",
    price: "6.5",
    gram: "180",
    calories: "110",
    spicy: 0,
    rating: 4.1,
  },
];

// 🟡 - Mains - 🟡
const menuMain = [
  {
    img: "../images/mains/meat/Chicken-and-Carrot-Curry.jpg",
    name: "Chicken and Curry",
    compound:
      "Tender chicken breast simmered in a rich coconut curry sauce with sweet glazed carrots and aromatic spices.",
    class: "mainsMeat",
    id: "mains",
    price: "16",
    gram: "400",
    calories: "580",
    spicy: 3,
    rating: 4.8,
  },
  {
    img: "../images/mains/meat/Hot-Chili-Meat.jpg",
    name: "Hot Chili Meat",
    compound:
      "Slow-cooked beef chunks in a fiery chili sauce with bell peppers, onions, and a hint of smoked paprika.",
    class: "mainsMeat",
    id: "mains",
    price: "19.5",
    gram: "350",
    calories: "650",
    spicy: 5,
    rating: 4.9,
  },
  {
    img: "../images/mains/meat/Pepper-Harmony-Chicken.jpg",
    name: "Pepper Chicken",
    compound:
      "Juicy chicken thighs sautéed with a colorful harmony of bell peppers and a cracked black pepper glaze.",
    class: "mainsMeat",
    id: "mains",
    price: "15",
    gram: "380",
    calories: "520",
    spicy: 2,
    rating: 4.6,
  },
  {
    img: "../images/mains/meat/Spicy-Herb-Meat.jpg",
    name: "Spicy Herb Meat",
    compound:
      "Grilled medallions of pork seasoned with a vibrant blend of fresh garden herbs and crushed red pepper.",
    class: "mainsMeat",
    id: "mains",
    price: "18",
    gram: "320",
    calories: "490",
    spicy: 4,
    rating: 4.7,
  },
  {
    img: "../images/mains/pizza/Cheesy-Meat-Pizza.jpg",
    name: "Cheesy Meat Pizza",
    compound:
      "Thin crust topped with premium mozzarella, pepperoni, Italian sausage, and savory ham on a tomato base.",
    class: "mainsPizza",
    id: "mains",
    price: "20",
    gram: "580",
    calories: "1350",
    spicy: 2,
    rating: 4.8,
  },
  {
    img: "../images/mains/pizza/Golden-Pepper-Pizza.jpg",
    name: "Golden Pepper Pizza",
    compound:
      "A vegetarian delight featuring golden bell peppers, sun-dried tomatoes, and extra virgin olive oil.",
    class: "mainsPizza",
    id: "mains",
    price: "17",
    gram: "520",
    calories: "980",
    spicy: 1,
    rating: 4.4,
  },
  {
    img: "../images/mains/pizza/Hawaiian-Meat-Pizza.jpg",
    name: "Hawaiian Meat Pizza",
    compound:
      "The classic tropical mix: juicy pineapple chunks, honey-glazed ham, and melted mozzarella cheese.",
    class: "mainsPizza",
    id: "mains",
    price: "18.5",
    gram: "550",
    calories: "1120",
    spicy: 0,
    rating: 4.2,
  },
  {
    img: "../images/mains/soup/Beetroot-Cream-Soup.jpg",
    name: "Beetroot Cream Soup",
    compound:
      "Velvety smooth beetroot purée with a touch of ginger, served with a dollop of sour cream and pumpkin seeds.",
    class: "mainsSoup",
    id: "mains",
    price: "9",
    gram: "300",
    calories: "240",
    spicy: 0,
    rating: 4.7,
  },
  {
    img: "../images/mains/soup/Creamy-Grain-Bowl.jpg",
    name: "Creamy Grain Bowl",
    compound:
      "A hearty and nutritious soup with pearled barley, wild mushrooms, and a delicate cream finish.",
    class: "mainsSoup",
    id: "mains",
    price: "10.5",
    gram: "350",
    calories: "310",
    spicy: 0,
    rating: 4.5,
  },
];

// 🟡 - Desserts - 🟡
const menuDesserts = [
  {
    img: "../images/desserts/cake/cherry-cake.jpg",
    name: "Cherry Cake",
    compound:
      "Layered sponge cake with fresh cherries, light cream cheese frosting, and a hint of vanilla.",
    class: "dessertsCake",
    id: "desserts",
    price: "8",
    gram: "180",
    calories: "420",
    spicy: 0,
    rating: 4.9,
  },
  {
    img: "../images/desserts/cake/chocolate-cupcake.jpg",
    name: "Chocolate Cupcake",
    compound:
      "Rich Belgian chocolate muffin with a molten center, topped with smooth ganache and chocolate chips.",
    class: "dessertsCake",
    id: "desserts",
    price: "5.5",
    gram: "120",
    calories: "380",
    spicy: 0,
    rating: 4.8,
  },
  {
    img: "../images/desserts/pie/pie.jpg",
    name: "Classic Fruit Pie",
    compound:
      "Traditional buttery crust filled with seasonal fruits and dusted with powdered sugar.",
    class: "dessertsPie",
    id: "desserts",
    price: "7",
    gram: "200",
    calories: "350",
    spicy: 0,
    rating: 4.6,
  },
];

// 🟡 - Drinks - 🟡
const menuDrinks = [
  {
    img: "../images/drinks/cold/coca-cola.jpg",
    name: "Coca Cola",
    compound:
      "Classic sparkling soft drink, served chilled with a slice of lemon and ice.",
    class: "drinksCold",
    id: "drinks",
    price: "3",
    ml: "330",
    calories: "140",
    spicy: 0,
    rating: 4.9,
  },
  {
    img: "../images/drinks/cocktails/cherry-fresh.jpg",
    name: "Cherry Fresh",
    compound:
      "Natural cold-pressed cherry juice with a splash of sparkling water and mint leaves.",
    class: "drinksCocktails",
    id: "drinks",
    price: "6",
    ml: "300",
    calories: "120",
    spicy: 0,
    rating: 4.7,
  },
  {
    img: "../images/drinks/cocktails/lemonade.jpg",
    name: "Homemade Lemonade",
    compound:
      "Refreshing citrus blend of fresh lemons, limes, and a touch of organic agave syrup.",
    class: "drinksCocktails",
    id: "drinks",
    price: "5.5",
    ml: "400",
    calories: "90",
    spicy: 0,
    rating: 4.8,
  },
  {
    img: "../images/drinks/cocktails/mojito.jpg",
    name: "Classic Mojito",
    compound:
      "Muddled fresh mint and lime, cane sugar, and soda water. A perfect thirst quencher.",
    class: "drinksCocktails",
    id: "drinks",
    price: "8.5",
    ml: "350",
    calories: "160",
    spicy: 0,
    rating: 4.9,
  },
  {
    img: "../images/drinks/beer/cinnamon-shot.jpg",
    name: "Cinnamon Shot",
    compound:
      "A spicy warming shot infused with natural cinnamon and a touch of honey.",
    class: "drinksBeer",
    id: "drinks",
    price: "4",
    ml: "50",
    calories: "85",
    spicy: 2,
    rating: 4.4,
  },
  {
    img: "../images/drinks/beer/lime-shot.jpg",
    name: "Lime Shot",
    compound:
      "A sharp and refreshing citrus shot made with premium lime zest and agave.",
    class: "drinksBeer",
    id: "drinks",
    price: "4",
    ml: "50",
    calories: "75",
    spicy: 1,
    rating: 4.5,
  },
  {
    img: "../images/drinks/beer/shot.jpg",
    name: "Classic Shot",
    compound: "Our house-special premium spirit shot, served ice cold.",
    class: "drinksBeer",
    id: "drinks",
    price: "4",
    ml: "50",
    calories: "70",
    spicy: 0,
    rating: 4.2,
  },
  {
    img: "../images/drinks/beer/whiskey.jpg",
    name: "Aged Whiskey",
    compound:
      "Select single malt whiskey with smoky notes and a long, smooth finish. Served neat or on the rocks.",
    class: "drinksBeer",
    id: "drinks",
    price: "12",
    ml: "50",
    calories: "110",
    spicy: 0,
    rating: 5.0,
  },
];

export { menuStarters, menuMain, menuDesserts, menuDrinks };
